{% set name = "naif_eop_high_prec" %}
{% set version = "2025.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/naif_eop_high_prec-{{ version }}.tar.gz
  sha256: b967f1c9f72836bb24ead1e9565da7fb31a523590528d224ce85a3f2e23dd6ec


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - naif_eop_high_prec
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: NAIF High Precision Earth Orientation Parameters (EOP) Kernel for SPICE
  home: https://github.com/B612-Asteroid-Institute/naif_eop_high_prec
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akoumjian
    - moeyensj
    - ntellis
    - KatKiker
